const repository = "hegeldev/hegel-rust";
const assetPattern = /^libhegel-[a-z0-9]+-[a-z0-9]+\.(so|dylib|dll)$/;
const requestedVersion = Deno.args[0]?.replace(/^v/, "");
const endpoint = requestedVersion
  ? `https://api.github.com/repos/${repository}/releases/tags/v${requestedVersion}`
  : `https://api.github.com/repos/${repository}/releases/latest`;

const headers: Record<string, string> = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
};
const token = Deno.env.get("GITHUB_TOKEN");
if (token) headers.Authorization = `Bearer ${token}`;

const response = await fetch(endpoint, { headers });
if (!response.ok) {
  throw new Error(`GitHub API returned ${response.status}: ${await response.text()}`);
}

const release: {
  tag_name: string;
  assets: Array<{ name: string; digest?: string | null }>;
} = await response.json();
const version = release.tag_name.replace(/^v/, "");
if (requestedVersion && version !== requestedVersion) {
  throw new Error(`requested release v${requestedVersion} but got tag ${release.tag_name}`);
}

const checksums = new Map<string, string>();
for (const asset of release.assets) {
  if (!assetPattern.test(asset.name)) continue;
  if (!asset.digest?.startsWith("sha256:")) {
    throw new Error(`asset ${asset.name}: expected a sha256 digest, got ${asset.digest}`);
  }
  checksums.set(asset.name, asset.digest.slice("sha256:".length));
}
if (checksums.size === 0) {
  throw new Error(`no .so/.dylib/.dll assets found in release v${version}`);
}

const entries = [...checksums]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, digest]) => `  ${JSON.stringify(name)}:\n    ${JSON.stringify(digest)},`)
  .join("\n");
const source = `// Code generated by scripts/update-checksums.ts; DO NOT EDIT.
//
// Run \`deno task update-checksums\` to pull in the latest hegel-rust release,
// then commit the result.

/**
 * SHA-256 checksums for the published libhegel release artifacts.
 *
 * The auto-downloader (\`locate.ts\`) verifies a downloaded artifact against the
 * entry for the host platform's asset before loading it. The digests are baked
 * into the source on purpose: fetching a checksum file from the same release it
 * is meant to verify provides no integrity guarantee, since a tampered release
 * would simply ship a matching checksum.
 *
 * @packageDocumentation
 */

/** The pinned libhegel version this client targets. */
export const LIBHEGEL_VERSION = ${JSON.stringify(version)};

/** Map from published asset filename to its SHA-256 hex digest. */
export const LIBHEGEL_CHECKSUMS: Readonly<Record<string, string>> = {
${entries}
};
`;

await Deno.writeTextFile(new URL("../src/checksums.ts", import.meta.url), source);
console.error(`libhegel release: v${version}`);
console.error(`wrote ${checksums.size} checksum(s) to src/checksums.ts`);
