// Code generated by scripts/update-checksums.ts; DO NOT EDIT.
//
// Run `deno task update-checksums` to pull in the latest hegel-rust release,
// then commit the result.

/**
 * SHA-256 checksums for the published libhegel release artifacts.
 *
 * The auto-downloader (`locate.ts`) verifies a downloaded artifact against the
 * entry for the host platform's asset before loading it. The digests are baked
 * into the source on purpose: fetching a checksum file from the same release it
 * is meant to verify provides no integrity guarantee, since a tampered release
 * would simply ship a matching checksum.
 *
 * @packageDocumentation
 */

/** The pinned libhegel version this client targets. */
export const LIBHEGEL_VERSION = "0.23.0";

/** Map from published asset filename to its SHA-256 hex digest. */
export const LIBHEGEL_CHECKSUMS: Readonly<Record<string, string>> = {
  "libhegel-darwin-arm64.dylib": "fdddf3e8bcd7bdda45c10a477e516b2782dd78d9b35e9516947c7b193becf0f0",
  "libhegel-linux-amd64.so": "dcb415b65a2a3c142bbf63b3e72ae7700c50f1aa7cb73d8d012532f156926f5a",
  "libhegel-linux-arm64.so": "c0d1c3e79f1bfcc45d0b5352fb04879e638cf92d816c2d40db1bd6da0eb9ad0a",
  "libhegel-windows-amd64.dll": "4931dbfb71d4811bbae957a47c651a24d597e9ab2e3633f9873b8193b9d93548",
  "libhegel-windows-arm64.dll": "2659253a4e868756386114cce3f153719b9bbe266c2c7821197317d090c43e66",
};
